[project]
name = "lightfinder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.6",
    "pillow>=11.1.0",
    "pydantic>=2.10.5",
]
